<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="prn_SlrySlip_Windows.aspx.cs" 
    Inherits="bncmc_payroll.admin.prn_SlrySlip_Windows" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title></title>
     <link href="css/style.css" rel="stylesheet" type="text/css" />
     <script type="text/javascript">
         function printME() {
             document.getElementById("btnPrint").style.display = "none";
             window.print();
             document.getElementById("btnPrint").style.display = "";
         }        
    </script>
</head>

<body style="background-color:White;">
    
    <form id="form1" runat="server" style="background-image:url(images/logo_Black.jpg)">
        <div>
            <asp:Literal ID="ltrContent" runat="server" />
             <br/><br/><br/>
            <div id="bottomRight">
            <table width="100%" cellpadding="2" cellspacing="2" border="0" >
                <tr>
                    <td colspan="3" align="right">
                        <input type="button" class="button" id="btnPrint" value= "Print" onclick="printME();" /> &nbsp;
                    </td>
                </tr>
            </table>
             </div>
    
        <div style="float:right;" id="bottomRight_Text">Report generated by Crocus IT Solutions</div>
        </div>
    </form>
</body>
</html>
