<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="prn_Reports.aspx.cs" Inherits="bncmc_payroll.Employee.prn_Reports" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title></title>
     <link href="../admin/css/style.css" rel="stylesheet" type="text/css" />
     <script type="text/javascript">
         function printME() {
             document.getElementById("btnPrint").style.display = "none";
             window.print();
             document.getElementById("btnPrint").style.display = "";
         }        
    </script>
     <link rel="stylesheet" type="text/css" href="http://cdn.webrupee.com/font">
    <style type="text/css">
		.LineRight
		{
			border-right:0.5px solid #424242
		}
		.LineLeft
		{
			border-left:0.5px solid #424242
		}
		.LineBottom
		{
			border-bottom:0.5px solid #424242
		}
		.LineTop
		{
			border-top:0.5px solid #424242
		}
		.LineAll
		{
			border:0.5px solid #424242
		}

		.textBold
		{
			font-weight:bold;
			text-align:Center;
			font-size:15pt;
		}
	</style>

    <style type="text/css">
        .table
        {
            border-top: 1px solid #e5eff8;
            border-right: 1px solid #e5eff8;
            margin: 1em auto;
            border-collapse: collapse;
            color: Black;
            background-color: #F2F2F2;
        }
        
        
        .table tr th
        {
            text-align: center;
            font: bold "Century Gothic" , "Trebuchet MS" ,Arial,Helvetica,sans-serif;
            background-color: gray;
            color: #fff;
        }
        
        
        .table tr.odd td
        {
            background: #f7fbff;
        }
        
        
        .table td
        {
            border-bottom: 1px solid #e5eff8;
            border-left: 1px solid #e5eff8;
            padding: .3em;
            text-align: left;
            color:Purple;
        }
        
         .table td.Caption
        {
            color:Black;
            font-weight:bold;
        }
        
         .table td.Data
        {
            color:Purple;
            font-weight:bold;
        }
    </style>
</head>

<body style="background-color:White;">
    
    <form id="form1" runat="server">
        <div>
        <div>
            <asp:Literal ID="ltrContent" runat="server" />
        </div>
            <br/><br/><br/>

            <div id="bottomRight">
            <table width="100%" cellpadding="2" cellspacing="2" border="0">
                <tr>
                    <td colspan="3" align="right">
                        <input type="button" class="button" id="btnPrint" value= "Print" onclick="printME();" /> &nbsp;
                    </td>
                </tr>
            </table>
            </div>

            <div style="float:right;" id="bottomRight_Text">Report generated by Crocus IT Solutions</div>
        </div>
    </form>
</body>
</html>
